### PR TITLE
Fix the 'now' line position

### LINKED ISSUE #129: The 'now' line in the agenda report is in the incorrect place in the morning
I noticed this around 02:00.

### PR DESCRIPTION
**Pull request by jecaro**
This fixes #129. 

The case when the current time is before the first `AgendaReportLine` wasn't taken into account. The `isBetween` function is not requiered any more, so I deleted it.

### CODE REVIEW

File: smos-query/src/Smos/Query/Commands/Agenda.hs [hunk 1]
```diff
@@ -113,16 +113,12 @@ insertHourLines now = go [8 .. 18]
...
-      (x : y : zs) ->
-        if isBetween x now y
-          then x : NowLine : y : zs
-          else x : go (y : zs)
+      go = \case
+        [] -> [NowLine]
+        (x : xs) ->
+          if isBefore now x
+            then NowLine : x : xs
+            else x : go xs
```
Comment (NorfairKing) [inline smos-query/src/Smos/Query/Commands/Agenda.hs:121]: Do I understand correctly that there will be no `NowLine` if the now line should go after the last `AgendaReportLine`?
Is that on purpose?

**Comment by NorfairKing** [comment]
Wow you found this bug, amazing. Thank you! I left a little comment but I'm already ok with merging as soon as the CI passes.

**Comment by NorfairKing** [comment]
I'm also redirecting this PR onto `development` instead of `master`. That shouldn't cause any problems, but make sure to be aware of that if you make any more changes.

File: smos-query/src/Smos/Query/Commands/Agenda.hs (hunk 1 above)
Comment (jecaro) [reply smos-query/src/Smos/Query/Commands/Agenda.hs:121]: This should not behave like this and the `NowLine` is inserted no matter what.
Indeed, in the recursive `go` function, if no `AgendaReportLine` validate the condition, the empty list stopping condition appends the `NowLine` at the end of `[AgendaReportLine]`.

**Comment by jecaro** [comment]
Ok, no problem. Thanks !

File: smos-query/src/Smos/Query/Commands/Agenda.hs (hunk 1 above)
Comment (NorfairKing) [reply smos-query/src/Smos/Query/Commands/Agenda.hs:121]: Ah yes, my bad!
